spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/youOweMeBeer_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5        # max. 5 současných spojení
      minimum-idle: 1             # drž jen 1 nečinné spojení
      idle-timeout: 15000         # 15s nečinnosti = zavři spojení
      max-lifetime: 60000         # max životnost spojení 60s
      connection-timeout: 3000    # 3s timeout při čekání na spojení

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8081
  servlet:
    context-path: /youOweMeBeer
